-- ============================================================
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
--  SHOPPING SYSTEM — Complete SQL Script
--  Covers: DDL | Cart ops | Checkout | Reporting | Functions
--  Compatible: MySQL 8+
-- ============================================================

-- ============================================================
--  PART 2 — CREATE TABLES FROM UML DIAGRAM
-- ============================================================

CREATE TABLE IF NOT EXISTS Products (
    id     INT            NOT NULL AUTO_INCREMENT,
    name   VARCHAR(100)   NOT NULL,
    price  DECIMAL(10,2)  NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Users (
    user_id   INT          NOT NULL AUTO_INCREMENT,
    username  VARCHAR(80)  NOT NULL,
    CONSTRAINT pk_users    PRIMARY KEY (user_id),
    CONSTRAINT uq_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS Cart (
    product_id  INT  NOT NULL,
    qty         INT  NOT NULL DEFAULT 1,
    CONSTRAINT pk_cart      PRIMARY KEY (product_id),
    CONSTRAINT fk_cart_prod FOREIGN KEY (product_id)
        REFERENCES Products (id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_cart_qty CHECK (qty > 0)
);

CREATE TABLE IF NOT EXISTS OrderHeader (
    order_id    INT       NOT NULL AUTO_INCREMENT,
    user_id     INT       NOT NULL,
    order_date  DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_order_header   PRIMARY KEY (order_id),
    CONSTRAINT fk_order_user     FOREIGN KEY (user_id)
        REFERENCES Users (user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS OrderDetails (
    order_id  INT  NOT NULL,
    prod_id   INT  NOT NULL,
    qty       INT  NOT NULL,
    CONSTRAINT pk_order_details   PRIMARY KEY (order_id, prod_id),
    CONSTRAINT fk_od_order        FOREIGN KEY (order_id)
        REFERENCES OrderHeader (order_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_od_product      FOREIGN KEY (prod_id)
        REFERENCES Products (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_od_qty         CHECK (qty > 0)
);

-- ============================================================
--  SEED DATA — products and users from the spec
-- ============================================================

INSERT INTO Products (id, name, price) VALUES
    (1, 'Coke',  10.00),
    (2, 'Chips',  5.00);

INSERT INTO Users (user_id, username) VALUES
    (1, 'Arnold'),
    (2, 'Sheryl');


-- ============================================================
--  PART 3 — ADD ITEMS TO THE CART
-- ============================================================

-- --- Add a Coke (product_id = 1) — does NOT exist yet → INSERT ---
SELECT 'CART BEFORE adding first Coke' AS step;
SELECT * FROM Cart;

IF EXISTS (SELECT 1 FROM Cart WHERE product_id = 1) THEN
    UPDATE Cart SET qty = qty + 1 WHERE product_id = 1;
ELSE
    INSERT INTO Cart (product_id, qty) VALUES (1, 1);
END IF;

SELECT 'CART AFTER adding Coke (qty should be 1)' AS step;
SELECT c.product_id, p.name, c.qty, p.price, (c.qty * p.price) AS line_total
FROM   Cart c JOIN Products p ON c.product_id = p.id;

-- --- Add a Coke again (product_id = 1) — EXISTS → UPDATE qty ---
IF EXISTS (SELECT 1 FROM Cart WHERE product_id = 1) THEN
    UPDATE Cart SET qty = qty + 1 WHERE product_id = 1;
ELSE
    INSERT INTO Cart (product_id, qty) VALUES (1, 1);
END IF;

SELECT 'CART AFTER adding Coke again (qty should be 2)' AS step;
SELECT c.product_id, p.name, c.qty, p.price, (c.qty * p.price) AS line_total
FROM   Cart c JOIN Products p ON c.product_id = p.id;

-- --- Add Chips (product_id = 2) — does NOT exist yet → INSERT ---
IF EXISTS (SELECT 1 FROM Cart WHERE product_id = 2) THEN
    UPDATE Cart SET qty = qty + 1 WHERE product_id = 2;
ELSE
    INSERT INTO Cart (product_id, qty) VALUES (2, 1);
END IF;

SELECT 'CART AFTER adding Chips (2x Coke, 1x Chips)' AS step;
SELECT c.product_id, p.name, c.qty, p.price, (c.qty * p.price) AS line_total
FROM   Cart c JOIN Products p ON c.product_id = p.id;


-- ============================================================
--  PART 4 — REMOVE ITEMS FROM THE CART
-- ============================================================

-- --- Remove one Coke (qty > 1 → subtract 1) ---
SELECT 'REMOVE: Coke qty > 1, so subtract 1' AS step;

IF (SELECT qty FROM Cart WHERE product_id = 1) > 1 THEN
    UPDATE Cart SET qty = qty - 1 WHERE product_id = 1;
ELSE
    DELETE FROM Cart WHERE product_id = 1;
END IF;

SELECT 'CART AFTER removing one Coke (should show qty = 1)' AS step;
SELECT c.product_id, p.name, c.qty FROM Cart c JOIN Products p ON c.product_id = p.id;

-- --- Remove Coke again (qty = 1 → delete the whole row) ---
SELECT 'REMOVE: Coke qty = 1, so delete the row entirely' AS step;

IF (SELECT qty FROM Cart WHERE product_id = 1) > 1 THEN
    UPDATE Cart SET qty = qty - 1 WHERE product_id = 1;
ELSE
    DELETE FROM Cart WHERE product_id = 1;
END IF;

SELECT 'CART AFTER removing last Coke (Coke row gone, only Chips remains)' AS step;
SELECT c.product_id, p.name, c.qty FROM Cart c JOIN Products p ON c.product_id = p.id;


-- ============================================================
--  PART 5 — CHECKOUT  (creates an order from current cart)
-- ============================================================

-- Reset cart to a known state for checkout demo
TRUNCATE TABLE Cart;
INSERT INTO Cart (product_id, qty) VALUES (1, 2), (2, 1);

SELECT 'CART BEFORE first checkout' AS step;
SELECT c.product_id, p.name, c.qty FROM Cart c JOIN Products p ON c.product_id = p.id;

-- ---- ORDER 1: User Arnold (user_id = 1) checks out ----

-- A: Insert order header
INSERT INTO OrderHeader (user_id, order_date) VALUES (1, '2015-04-15 15:30:00');
SET @order1_id = LAST_INSERT_ID();

SELECT CONCAT('Order header created — OrderID = ', @order1_id) AS step;
SELECT * FROM OrderHeader WHERE order_id = @order1_id;

-- B: Copy cart lines into order details, then clear the cart
INSERT INTO OrderDetails (order_id, prod_id, qty)
SELECT @order1_id, product_id, qty FROM Cart;

DELETE FROM Cart;

SELECT 'ORDER DETAILS after first checkout' AS step;
SELECT * FROM OrderDetails WHERE order_id = @order1_id;

SELECT 'CART after first checkout (should be empty)' AS step;
SELECT * FROM Cart;

-- ---- ORDER 2: User Sheryl (user_id = 2) checks out ----

-- Re-fill cart for second order
INSERT INTO Cart (product_id, qty) VALUES (1, 1), (2, 3);

SELECT 'CART BEFORE second checkout' AS step;
SELECT c.product_id, p.name, c.qty FROM Cart c JOIN Products p ON c.product_id = p.id;

INSERT INTO OrderHeader (user_id, order_date) VALUES (2, NOW());
SET @order2_id = LAST_INSERT_ID();

INSERT INTO OrderDetails (order_id, prod_id, qty)
SELECT @order2_id, product_id, qty FROM Cart;

DELETE FROM Cart;

SELECT CONCAT('Order 2 created — OrderID = ', @order2_id) AS step;
SELECT 'CART after second checkout (should be empty)' AS step;
SELECT * FROM Cart;


-- ============================================================
--  REPORTING — SELECT with INNER JOINS
-- ============================================================

-- ---- Print ALL orders (both orders, all lines) ----
SELECT 'ALL ORDERS — inner join across 3 tables' AS report;

SELECT
    oh.order_id,
    u.username,
    oh.order_date,
    p.name        AS product,
    od.qty,
    p.price,
    (od.qty * p.price) AS line_total
FROM OrderHeader oh
INNER JOIN Users        u  ON oh.user_id  = u.user_id
INNER JOIN OrderDetails od ON oh.order_id = od.order_id
INNER JOIN Products     p  ON od.prod_id  = p.id
ORDER BY oh.order_id, p.name;

-- ---- Print a SINGLE order (Order 1 only) ----
SELECT 'SINGLE ORDER — OrderID 1' AS report;

SELECT
    oh.order_id,
    u.username,
    oh.order_date,
    p.name        AS product,
    od.qty,
    p.price,
    (od.qty * p.price) AS line_total
FROM OrderHeader oh
INNER JOIN Users        u  ON oh.user_id  = u.user_id
INNER JOIN OrderDetails od ON oh.order_id = od.order_id
INNER JOIN Products     p  ON od.prod_id  = p.id
WHERE oh.order_id = 1;

-- ---- Print ALL ORDERS for a specific day (15 Apr 2015) ----
SELECT "ALL ORDERS for 15 Apr 2015" AS report;

SELECT
    oh.order_id,
    u.username,
    oh.order_date,
    p.name        AS product,
    od.qty,
    p.price,
    (od.qty * p.price) AS line_total
FROM OrderHeader oh
INNER JOIN Users        u  ON oh.user_id  = u.user_id
INNER JOIN OrderDetails od ON oh.order_id = od.order_id
INNER JOIN Products     p  ON od.prod_id  = p.id
WHERE DATE(oh.order_date) = '2015-04-15'
ORDER BY oh.order_id;

-- ---- Order totals summary per order ----
SELECT 'ORDER TOTALS SUMMARY' AS report;

SELECT
    oh.order_id,
    u.username,
    oh.order_date,
    SUM(od.qty * p.price) AS order_total
FROM OrderHeader oh
INNER JOIN Users        u  ON oh.user_id  = u.user_id
INNER JOIN OrderDetails od ON oh.order_id = od.order_id
INNER JOIN Products     p  ON od.prod_id  = p.id
GROUP BY oh.order_id, u.username, oh.order_date
ORDER BY oh.order_id;


-- ============================================================
--  BONUS — STORED FUNCTIONS FOR CART OPERATIONS
-- ============================================================

DROP FUNCTION IF EXISTS AddToCart;
DROP FUNCTION IF EXISTS RemoveFromCart;

DELIMITER $$

-- ----------------------------------------------------------
-- AddToCart(p_product_id INT)
--   If item exists in cart → qty + 1
--   If item does not exist  → insert with qty = 1
--   Returns the new qty
-- ----------------------------------------------------------
CREATE FUNCTION AddToCart(p_product_id INT)
RETURNS INT
READS SQL DATA
MODIFIES SQL DATA
DETERMINISTIC
BEGIN
    DECLARE v_qty INT DEFAULT 0;

    SELECT qty INTO v_qty FROM Cart WHERE product_id = p_product_id LIMIT 1;

    IF v_qty > 0 THEN
        UPDATE Cart SET qty = qty + 1 WHERE product_id = p_product_id;
        SET v_qty = v_qty + 1;
    ELSE
        INSERT INTO Cart (product_id, qty) VALUES (p_product_id, 1);
        SET v_qty = 1;
    END IF;

    RETURN v_qty;
END$$

-- ----------------------------------------------------------
-- RemoveFromCart(p_product_id INT)
--   If qty > 1 → subtract 1
--   If qty = 1 → delete the row
--   Returns remaining qty (0 means row deleted)
-- ----------------------------------------------------------
CREATE FUNCTION RemoveFromCart(p_product_id INT)
RETURNS INT
READS SQL DATA
MODIFIES SQL DATA
DETERMINISTIC
BEGIN
    DECLARE v_qty INT DEFAULT 0;

    SELECT qty INTO v_qty FROM Cart WHERE product_id = p_product_id LIMIT 1;

    IF v_qty > 1 THEN
        UPDATE Cart SET qty = qty - 1 WHERE product_id = p_product_id;
        SET v_qty = v_qty - 1;
    ELSEIF v_qty = 1 THEN
        DELETE FROM Cart WHERE product_id = p_product_id;
        SET v_qty = 0;
    END IF;

    RETURN v_qty;
END$$

DELIMITER ;


-- ============================================================
--  BONUS DEMO — using the stored functions
-- ============================================================

TRUNCATE TABLE Cart;

SELECT 'FUNCTION DEMO — AddToCart' AS step;
SELECT AddToCart(1) AS coke_qty_after_add;      -- insert Coke, qty = 1
SELECT AddToCart(1) AS coke_qty_after_add;      -- update Coke, qty = 2
SELECT AddToCart(2) AS chips_qty_after_add;     -- insert Chips, qty = 1

SELECT 'Cart after function adds:' AS step;
SELECT c.product_id, p.name, c.qty
FROM Cart c JOIN Products p ON c.product_id = p.id;

SELECT 'FUNCTION DEMO — RemoveFromCart' AS step;
SELECT RemoveFromCart(1) AS coke_qty_after_remove;   -- qty 2 → 1
SELECT RemoveFromCart(1) AS coke_qty_after_remove;   -- qty 1 → 0 (row deleted)

SELECT 'Cart after function removes (only Chips should remain):' AS step;
SELECT c.product_id, p.name, c.qty
FROM Cart c JOIN Products p ON c.product_id = p.id;

-- ============================================================
--  END OF SCRIPT
-- ============================================================
